/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { QrAnimations } from "./components/bitcoin-qr/bitcoin-qr";
export { QrAnimations } from "./components/bitcoin-qr/bitcoin-qr";
export namespace Components {
    interface BitcoinQr {
        "animateQRCode": (animation?: QrAnimations) => Promise<void>;
        "bitcoin": string;
        "callback": () => void;
        "imgSrc": string;
        "interval": number;
        "isPolling": boolean;
        "lightning": string;
        "moduleColor": string;
        "parameters": string;
        "positionCenterColor": string;
        "positionRingColor": string;
        "unified": string;
    }
}
declare global {
    interface HTMLBitcoinQrElement extends Components.BitcoinQr, HTMLStencilElement {
    }
    var HTMLBitcoinQrElement: {
        prototype: HTMLBitcoinQrElement;
        new (): HTMLBitcoinQrElement;
    };
    interface HTMLElementTagNameMap {
        "bitcoin-qr": HTMLBitcoinQrElement;
    }
}
declare namespace LocalJSX {
    interface BitcoinQr {
        "bitcoin"?: string;
        "callback"?: () => void;
        "imgSrc"?: string;
        "interval"?: number;
        "isPolling"?: boolean;
        "lightning"?: string;
        "moduleColor"?: string;
        "parameters"?: string;
        "positionCenterColor"?: string;
        "positionRingColor"?: string;
        "unified"?: string;
    }
    interface IntrinsicElements {
        "bitcoin-qr": BitcoinQr;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bitcoin-qr": LocalJSX.BitcoinQr & JSXBase.HTMLAttributes<HTMLBitcoinQrElement>;
        }
    }
}
