name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Yarn
        run: npm install -g yarn  # Install Yarn globally on the runner

      - name: Install dependencies and build
        run: |
          yarn install
          yarn build  # Replace with your actual build script from package.json
        working-directory: ./examples/sveltekit-kitchen-sink # Target the subfolder

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: 'build/*' # Or wherever your build output is
          target: '/var/www/bitcoin-qr'
          rm: true
          strip_components: 1
